name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with PlatformIO
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Run PlatformIO
        run: platformio run

  documentation:
    runs-on: ubuntu-latest
    name: Create the documentation
    steps:
      - uses: actions/checkout@v1
      - name: Install vuepress
        run: npm install -g vuepress
      - name: Build documentation
        run: npm run docs:build
